# Generated by Django 5.2.9 on 2025-12-09 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundSourceGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, help_text='Game-specific comments about this sound source.', verbose_name='Song Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_source_relationships', to='games.game', verbose_name='Game')),
                ('sound_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_relationships', to='sources.soundsource', verbose_name='Sound Source')),
            ],
            options={
                'verbose_name': 'Sound Source Game',
                'verbose_name_plural': 'Sound Source Games',
                'ordering': ['game__title', 'sound_source__name'],
                'unique_together': {('sound_source', 'game')},
            },
        ),
        migrations.AlterField(
            model_name='soundsource',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='sound_sources', through='sources.SoundSourceGame', to='games.game', verbose_name='Games'),
        ),
    ]
