# Generated by Django 5.2.9 on 2025-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='album_artists',
            field=models.ManyToManyField(blank=True, related_name='album_credits', to='songs.person', verbose_name='Album Artists'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.gametag', verbose_name='Tags'),
        ),
    ]
