# Generated by Django 5.2.9 on 2025-12-05 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_initial'),
        ('songs', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='users', to='sources.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='song',
            name='arrangers',
            field=models.ManyToManyField(blank=True, related_name='arranged_songs', to='songs.person', verbose_name='Arrangers'),
        ),
        migrations.AddField(
            model_name='song',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='composed_songs', to='songs.person', verbose_name='Composers'),
        ),
        migrations.AddField(
            model_name='song',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='games.game', verbose_name='Game'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'game')},
        ),
    ]
